apiVersion: v1
kind: Service
metadata:
  labels:
    app: hw1
  name: hw1
spec:
  clusterIP: None
  ports:
    - port: 9112
      name: petabridge-cmd
    - port: 4056
      name: akka-net
  selector:
    app: hw1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hw1
  labels:
    app: hw1
spec:
  serviceName: hw1
  replicas: 2
  selector:
    matchLabels:
      app: hw1
  template:
    metadata:
      labels:
        app: hw1
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: hw1
          #image: gcr.io/cs647-240119/hw1:v1
          image: hw1:latest
          # Use Never for local minikube, Always for gcr.io
          imagePullPolicy: Never #Always #Never
          ports:
            - containerPort: 4056
              name: akka-net
            - containerPort: 9112
              name: petabridge-cmd
          resources:
            limits:
              cpu: "500m"
              memory: 256M
            requests:
              cpu: "500m"
              memory: 128M
          env:
            # akka seeds will be hw1-{n}.$AKKA_SEED_PATH for each n
            - name: AKKA_SEED_PATH
              value: "hw1.default.svc.cluster.local"
          readinessProbe:
            tcpSocket:
              port: 4056
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: actor-data
              mountPath: /akkadata
  volumeClaimTemplates:
    - metadata:
        name: actor-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
